<?php
//
//
//// Store Complex Grouping preprocess theme functions in a separate .inc file.
//\Drupal::moduleHandler()->loadInclude('views_complex_grouping', 'inc', 'views_complex_grouping.theme');
//
//
///**
// * Implements hook_theme().
// */
function views_complex_grouping_theme($existing, $type, $theme, $path) {
  return [
      'views_complex_grouping_leave' => [
          'variables' => [
              'test_var' => NULL,
              'view' => NULL,
              'grouping' => NULL,
              'grouping_level' => NULL,
              'grouping_branch' => NULL,
              'rows' => [],
              'content' => NULL,
              'title' => '',
              'fields' => []

          ],
      ],
  ];
}
